### ISSUE TITLE
Tell me the advantage of your extension.

### ISSUE THREAD

**Issue by zydjohnHotmail** [cracker4o/purge-cf-cache-chrome-extension#5]
Hello:
I looked at your extension, it seems to be rather interesting.  But I don’t quite understand its usage.  I have one specific web site, which I can install Privacy Pass extension to use the web site for some time, the Privacy Pass extension can be downloaded from here: 
https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi?hl=en
The web site, which I can use Privacy Pass extension is https://www.buffbet.com
If you install the extension, then after the first time you solve the hCaptcha challenge, you will be given 5 tokens or credits.  Then, with each token or credit, you can visit the web site for about 2 hours, so totally, you can visit the web site for about 12 hours (plus the first one by hand).
You can do some testing to know what I am talking about.
I want to know if I install your extension, what I can get if I want to visit the same web site?
If I can get more tokens or credits, or if I can get longer time to visit the web site, like 20 hours, then your extension is useful.  If I can use your extension to visit that web site for more than one day, then it is nearly perfect.
But I have no idea, what I can get for using your extension on some web sites, which use hCaptcha challenges.
Thanks,

**Comment by cracker4o** [comment]
Hi zydjohnHotmail. My extension is not suitable for your use case. It is intended for website owners and not for the users of a website. The idea of the CF-Purge extension is to clear the CloudFlare CDN cache of a specific web page that was cached in CloudFlare's content delivery network. 
Here is a classic use case for my extension:
- you create a website
- you configure your website to use the CloudFlare Content Delivery Network so you can serve it's web pages and resources instantly fast in any world region
- As a website owner, from time to time you need to update some information on a web page which requires you to clear the CDN cache for that web page. 
- You can use my extension to navigate to that page of your website and clear the cache since you are the owner.
